name: zig build test
on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install libcairo2-dev libpango1.0-dev pkg-config wayland-protocols libwayland-bin libwayland-dev dbus libdbus-1-3 libdbus-1-dev
      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v2
        with:
          version: 0.13.0

      - name: Test
        run: zig build test
